# -*- coding: utf-8 -*-
"""IPAddressG-Town.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VFPR3mExISTX0ZbJmzzgNRUlDmsv9Cty
"""

!pip install bs4
!pip install requests
!pip install html5lib
!pip install folium



import requests
import folium

api_key = '{api_key}'
#add IP to end of URL

f = open('/content/IPAdressesTXT.txt').read()
results = []
for ip in f.splitlines():
  url = "https://api.apilayer.com/ip_to_location/" + ip
  payload = {}
  headers= {
  "apikey": api_key
  }
  response = requests.request("GET", url, headers=headers, data = payload)
  results.append(response.text)

def getNums(s):
  result = ''
  for c in s:
     if c.isnumeric() or c == '.' or c == '-':
      result += c
  return float(result)

pointList = []
#(Lat, Long)
for w in results:
  pointList.append((getNums(w.splitlines()[3]), getNums(w.splitlines()[4])))

with open('coordinates.txt', 'w') as f:
  f.write(str(pointList))