# -*- coding: utf-8 -*-
"""IPAddressG-TownMapMaker.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VFPR3mExISTX0ZbJmzzgNRUlDmsv9Cty
"""

!pip install folium



import folium
import folium.plugins
import matplotlib as plt
import ast

coords = open('/coordinates.txt').read()
coords = coords[1:]
coords = ast.literal_eval(coords)

m = folium.Map()
folium.plugins.HeatMap(coords, name='Heat Map').add_to(m)

for p in coords:
  folium.CircleMarker(location=p, radius=5, fill=True, fill_color='blue', color='white', fill_opacity=0.8).add_to(m)

folium.LayerControl().add_to(m)
m.save('GtownMap.html')